name       : haskell-hinotify
version    : 0.3.10
release    : 2
source     :
    - https://hackage.haskell.org/package/hinotify-0.3.10/hinotify-0.3.10.tar.gz : af2b7d5733ab52ca38f0d9aed1ec37304f1d6964caa0fb556b8215858c1d5d9d
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library provides a wrapper to the Linux Kernel's inotify feature, allowing applications to subscribe to notifications when a file is accessed or modified.
description: "This library provides a wrapper to the Linux Kernel's inotify feature, allowing applications to subscribe to notifications when a file is accessed or modified. \n"
builddeps  :
    - haskell-async
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
