name       : haskell-hinotify
version    : '0.4'
release    : 3
source     :
    - https://hackage.haskell.org/package/hinotify-0.4/hinotify-0.4.tar.gz : 7d182c524384aaa15eec666803643d067671e8e806f315c10758685e90a934f4
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library provides a wrapper to the Linux Kernel's inotify feature, allowing applications to subscribe to notifications when a file is accessed or modified.
description: |
    This library provides a wrapper to the Linux Kernel's inotify feature, allowing applications to subscribe to notifications when a file is accessed or modified.
builddeps  :
    - haskell-async-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - haskell-async-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
