name       : haskell-hinotify
version    : 0.3.9
release    : 1
source     :
    - http://hackage.haskell.org/package/hinotify-0.3.9/hinotify-0.3.9.tar.gz : f2480e4c08a516831c2221eebc6a9d3242e892932d9315c34cbe92a101c5df99
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library provides a wrapper to the Linux Kernel's inotify feature, allowing applications to subscribe to notifications when a file is accessed or modified. 
description: |
    This library provides a wrapper to the Linux Kernel's inotify feature, allowing applications to subscribe to notifications when a file is accessed or modified. 
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
